services:
  frontend:
    ports:
      - "80:80"

  gateway:
    command: flask --app main:app run --host=0.0.0.0 --port=8000 --debug

  auth-service:
    command: flask --app main:app run --host=0.0.0.0 --port=5000 --debug

  ticket-service:
    command: flask --app main:app run --host=0.0.0.0 --port=5000 --debug
    extra_hosts:
      - "host.docker.internal:host-gateway"

  message-service:
    command: flask --app main:app run --host=0.0.0.0 --port=5000 --debug

  notification-service:
    command: flask --app main:app run --host=0.0.0.0 --port=5000 --debug