version: "3.9"

services:

  gateway:
    build: ./api-gateway
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./api-gateway:/app

  auth-service:
    build: ./services/auth-service
    ports:
      - "5001:5000"
    env_file:
      - .env
    volumes:
      - ./services/auth-service:/app
      - ./shared:/shared

  ticket-service:
    build: ./services/ticket-service
    ports:
      - "5002:5000"
    env_file:
      - .env
    volumes:
      - ./services/ticket-service:/app
      - ./shared:/shared
      - C:/Users/ebravo/Desktop/archivos:/app/uploads

  message-service:
    build: ./services/message-service
    ports:
      - "5003:5000"
    env_file:
      - .env
    volumes:
      - ./services/message-service:/app
      - ./shared:/shared
      - C:/Users/ebravo/Desktop/archivos:/app/uploads

  frontend:
    build: ./frontend
    container_name: mda-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: ${DB_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data: